name: flutter_gallery
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fast_cached_network_image: ^1.2.9
  cached_network_image: ^3.3.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  go_router: ^14.2.0
  http: ^1.2.1 
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.3
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env

